### ISSUE TITLE
O framework consiste apenas em relação ao banco de dados ?

### ISSUE THREAD

**Issue by ianpatricck** [aleDsz/rarframework#1]
Faala Alexandre blz?, eu estava dando uma olhada aqui no seu projeto e gostei bastante da ideia de automatizar códigos e poupar tempo, também tenho um projeto semelhante. Não seria melhor expandir mais o nível de automação além para o banco de dados, seja ele MySQL, PostgreSQL e etc ... ? como criar algo relacionado a rotas envio de formulários.

**Comment by aleDsz** [comment]
Mas o intuito dessa lib não é se tornar algo parecido com o Laravel, estou apenas criando uma lib para cuidar de banco de dados

Esse foi para o meu TCC hahahaha

**Comment by ianpatricck** [comment]
✌️

**Comment by aleDsz** [comment]
Eu tô refazendo ele na branch **development**

**Comment by ianpatricck** [comment]
depois de longos 4 anos kkk.
